POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "johndoe",
  "password": "123456"
}

###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "marydoe",
  "password": "123456"
}

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "marydoe",
  "password": "123456"
}

###

GET http://localhost:3000/auth/test-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZGE5YTdkZi03NTk0LTRhYzgtYWQ1Ny01YTAxNTZiZGI2YjQiLCJ1c2VybmFtZSI6ImpvaG5kb2UiLCJpYXQiOjE2OTg5NTM0NDgsImV4cCI6MTY5ODk1MzUwOH0.2KlLVgWdd5z4f2DqN6t3ZAwgTv5yNLVEhsK5rP5_bQo